import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import iranSansLocal from "next/font/local";
import "./globals.css";
import { Header } from "@/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iranSans = iranSansLocal({
  src: "../assets/fonts/Iranian Sans.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl" className={`${iranSans.className} antialiased`}>
        <Header />
        <div className="holder px-10">{children}</div>
      </body>
    </html>
  );
}
